wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713511857.0
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 23
      4: 3.10.10
      5: 0.16.6
      6: 4.39.3
      8:
      - 1
      - 5
      13: linux-x86_64
